/**
 * Task Automation & Scheduled Compliance Engine Service
 *
 * Implements:
 * 1. Task Lifecycle Management (Open, In Progress, Pending Approval, Completed, Overdue, Cancelled)
 * 2. Automated Task Generation for:
 *    - Compliance approaching expiry (30d, 15d, 7d, 1d milestones)
 *    - Compliance expired
 *    - Pending approval
 *    - Missing documents
 *    - Overdue compliance
 * 3. Strict Duplicate Prevention using autoGenKey & active task guards
 * 4. Multi-channel Notification triggering
 */

import { Types } from 'mongoose';
import Task, { ITask } from '../models/Task.js';
import ComplianceRecord, { IComplianceRecord } from '../models/ComplianceRecord.js';
import User from '../models/User.js';
import Settings from '../models/Settings.js';
import { auditService } from './audit.service.js';
import { NotificationService } from './notification.service.js';
import { emitTaskAssigned } from './socket.service.js';
import { ApiError } from '../utils/apiError.js';
import { ROLES } from '../constants/permissions.js';
import type { TaskStatus, TaskPriority } from '../types/models.js';

export interface CreateTaskInput {
  title: string;
  description?: string;
  entity: string | Types.ObjectId;
  location?: string | Types.ObjectId;
  complianceRecord?: string | Types.ObjectId;
  assignedTo: string | Types.ObjectId;
  priority?: TaskPriority;
  dueDate: Date | string;
  status?: TaskStatus;
  taskType?: 'renewal' | 'approval' | 'document_upload' | 'inspection' | 'manual';
  createdBy?: string | Types.ObjectId;
}

export interface TaskQueryParams {
  page?: number;
  limit?: number;
  search?: string;
  status?: string;
  priority?: string;
  entity?: string;
  location?: string;
  assignedTo?: string;
  myTasks?: boolean;
  overdueOnly?: boolean;
  dueDateFrom?: string;
  dueDateTo?: string;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export class TaskAutomationService {
  /**
   * 1. Create a Task (Manual or Triggered)
   */
  public static async createTask(input: CreateTaskInput): Promise<ITask> {
    const task = await Task.create({
      title: input.title,
      description: input.description,
      entity: input.entity,
      location: input.location,
      complianceRecord: input.complianceRecord,
      assignedTo: input.assignedTo,
      priority: input.priority || 'medium',
      dueDate: new Date(input.dueDate),
      status: input.status || 'open',
      taskType: input.taskType || 'manual',
      createdBy: input.createdBy,
      isAutoGenerated: false,
    });

    // Populate for notifications & socket
    const populated = await Task.findById(task._id)
      .populate('entity', 'name entityCode')
      .populate('location', 'name locationCode')
      .populate('assignedTo', 'firstName lastName email fullName')
      .populate('createdBy', 'firstName lastName email fullName');

    // Trigger Notification to Assignee
    await NotificationService.dispatchNotification({
      recipientId: input.assignedTo,
      type: 'task_assigned',
      title: `New Task Assigned: ${task.title}`,
      body: task.description || `You have been assigned a task due on ${new Date(task.dueDate).toLocaleDateString()}.`,
      actionUrl: `/tasks`,
      relatedTask: task._id,
      entity: task.entity,
      emailData: {
        taskTitle: task.title,
        priority: task.priority,
        dueDate: new Date(task.dueDate).toLocaleDateString(),
        description: task.description,
        entityName: (populated?.entity as any)?.name,
        locationName: (populated?.location as any)?.name,
      },
    });

    emitTaskAssigned(input.assignedTo.toString(), populated || task);

    return populated || task;
  }

  /**
   * 2. Query Tasks with pagination, search, status metrics, and RBAC scoping
   */
  public static async getTasks(
    params: TaskQueryParams,
    userContext?: { userId: string; role: string; entityId?: string | null; locationId?: string | null }
  ) {
    const page = params.page || 1;
    const limit = params.limit || 10;
    const skip = (page - 1) * limit;

    const filter: Record<string, any> = {};

    // RBAC Entity Scoping
    if (userContext) {
      if (userContext.role === ROLES.ENTITY_ADMIN && userContext.entityId) {
        filter.entity = new Types.ObjectId(userContext.entityId);
      } else if (userContext.role === ROLES.LOCATION_MANAGER && userContext.locationId) {
        filter.location = new Types.ObjectId(userContext.locationId);
      }
    }

    // Explicit Filters
    if (params.myTasks && userContext) {
      filter.assignedTo = new Types.ObjectId(userContext.userId);
    } else if (params.assignedTo) {
      filter.assignedTo = new Types.ObjectId(params.assignedTo);
    }

    if (params.overdueOnly) {
      filter.status = { $ne: 'completed' };
      filter.dueDate = { $lt: new Date() };
    } else if (params.status && params.status !== 'all') {
      filter.status = params.status;
    }

    if (params.priority && params.priority !== 'all') {
      filter.priority = params.priority;
    }

    if (params.entity) {
      filter.entity = new Types.ObjectId(params.entity);
    }

    if (params.location) {
      filter.location = new Types.ObjectId(params.location);
    }

    if (params.dueDateFrom || params.dueDateTo) {
      filter.dueDate = {};
      if (params.dueDateFrom) filter.dueDate.$gte = new Date(params.dueDateFrom);
      if (params.dueDateTo) filter.dueDate.$lte = new Date(params.dueDateTo);
    }

    if (params.search) {
      const searchRegex = new RegExp(params.search.trim(), 'i');
      filter.$or = [{ title: searchRegex }, { description: searchRegex }];
    }

    // Sorting
    const sortField = params.sortBy || 'dueDate';
    const sortDirection = params.sortOrder === 'desc' ? -1 : 1;
    const sortOptions: Record<string, 1 | -1> = { [sortField]: sortDirection };

    const [tasks, total, metricsAggregation] = await Promise.all([
      Task.find(filter)
        .sort(sortOptions)
        .skip(skip)
        .limit(limit)
        .populate('entity', 'name entityCode')
        .populate('location', 'name locationCode')
        .populate('complianceRecord', 'recordNumber status dueDate expiryDate')
        .populate('assignedTo', 'firstName lastName email fullName avatar')
        .populate('completedBy', 'firstName lastName email fullName')
        .populate('createdBy', 'firstName lastName email fullName'),
      Task.countDocuments(filter),
      Task.aggregate([
        ...(filter.entity ? [{ $match: { entity: filter.entity } }] : []),
        {
          $group: {
            _id: '$status',
            count: { $sum: 1 },
          },
        },
      ]),
    ]);

    // Real Metrics
    const metrics = {
      total: 0,
      open: 0,
      in_progress: 0,
      pending_approval: 0,
      completed: 0,
      overdue: 0,
      cancelled: 0,
    };

    metricsAggregation.forEach((g) => {
      const key = g._id as keyof typeof metrics;
      if (metrics[key] !== undefined) {
        metrics[key] = g.count;
      }
      metrics.total += g.count;
    });

    // Also count actual overdue tasks
    const now = new Date();
    metrics.overdue = await Task.countDocuments({
      ...(filter.entity ? { entity: filter.entity } : {}),
      status: { $in: ['open', 'in_progress', 'pending_approval'] },
      dueDate: { $lt: now },
    });

    return {
      tasks,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit) || 1,
      },
      metrics,
    };
  }

  /**
   * 3. Get Task by ID
   */
  public static async getTaskById(id: string): Promise<ITask> {
    const task = await Task.findById(id)
      .populate('entity', 'name entityCode address')
      .populate('location', 'name locationCode address')
      .populate('complianceRecord', 'recordNumber status dueDate expiryDate rule')
      .populate('assignedTo', 'firstName lastName email fullName role avatar')
      .populate('completedBy', 'firstName lastName email fullName')
      .populate('createdBy', 'firstName lastName email fullName')
      .populate('comments.author', 'firstName lastName email fullName avatar');

    if (!task) throw ApiError.notFound('Task not found.');
    return task;
  }

  /**
   * 4. Update Task Status
   */
  public static async updateTaskStatus(
    id: string,
    newStatus: TaskStatus,
    userContext?: { userId: string; email: string }
  ): Promise<ITask> {
    const task = await Task.findById(id);
    if (!task) throw ApiError.notFound('Task not found.');

    const previousStatus = task.status;
    task.status = newStatus;

    if (newStatus === 'completed') {
      task.completedAt = new Date();
      if (userContext?.userId) {
        task.completedBy = new Types.ObjectId(userContext.userId);
      }
    } else {
      task.completedAt = undefined;
      task.completedBy = undefined;
    }

    if (newStatus === 'in_progress' && !task.startedAt) {
      task.startedAt = new Date();
    }

    task.updatedBy = userContext?.userId ? new Types.ObjectId(userContext.userId) : undefined;
    await task.save();

    // Audit Log
    if (userContext?.userId) {
      await auditService.logMutation({
        userId: userContext.userId,
        action: newStatus === 'completed' ? 'TASK_COMPLETED' : 'TASK_UPDATED',
        module: 'tasks',
        entityType: 'Task',
        recordId: task._id,
        entityId: task.entity as Types.ObjectId,
        previousValue: { status: previousStatus },
        newValue: { status: newStatus },
        description: `Task "${task.title}" status changed from ${previousStatus} to ${newStatus}`,
      });
    }

    return this.getTaskById(id);
  }

  /**
   * General Update Task
   */
  public static async updateTask(
    id: string,
    updateData: any,
    userId?: string
  ): Promise<ITask> {
    const task = await Task.findById(id);
    if (!task) throw ApiError.notFound('Task not found.');

    const previousStatus = task.status;

    if (updateData.status) {
      task.status = updateData.status;
      if (updateData.status === 'completed') {
        task.completedAt = new Date();
        if (userId) {
          task.completedBy = new Types.ObjectId(userId);
        }
      } else if (previousStatus === 'completed' && updateData.status !== 'completed') {
        task.completedAt = undefined;
        task.completedBy = undefined;
      }
      if (updateData.status === 'in_progress' && !task.startedAt) {
        task.startedAt = new Date();
      }
    }

    if (updateData.title) task.title = updateData.title;
    if (updateData.description !== undefined) task.description = updateData.description;
    if (updateData.priority) task.priority = updateData.priority;
    if (updateData.dueDate !== undefined) task.dueDate = updateData.dueDate;
    if (updateData.assignedTo !== undefined) task.assignedTo = updateData.assignedTo;

    if (userId) {
      task.updatedBy = new Types.ObjectId(userId);
    }

    await task.save();

    if (userId && updateData.status && previousStatus !== updateData.status) {
      await auditService.logMutation({
        userId,
        action: updateData.status === 'completed' ? 'TASK_COMPLETED' : 'TASK_UPDATED',
        module: 'tasks',
        entityType: 'Task',
        recordId: task._id,
        entityId: task.entity as Types.ObjectId,
        previousValue: { status: previousStatus },
        newValue: { status: updateData.status },
        description: `Task "${task.title}" status changed from ${previousStatus} to ${updateData.status}`,
      });
    }

    return this.getTaskById(id);
  }

  /**
   * Delete Task
   */
  public static async deleteTask(id: string): Promise<void> {
    const task = await Task.findByIdAndDelete(id);
    if (!task) throw ApiError.notFound('Task not found.');
  }

  /**
   * Task Metrics (counters for dashboard and views)
   */
  public static async getTaskMetrics(userId?: string): Promise<{
    total: number;
    open: number;
    inProgress: number;
    pendingApproval: number;
    completed: number;
    overdue: number;
    cancelled: number;
  }> {
    const query: any = {};
    if (userId) {
      query.assignedTo = new Types.ObjectId(userId);
    }

    const [total, open, inProgress, pendingApproval, completed, overdue, cancelled] =
      await Promise.all([
        Task.countDocuments(query),
        Task.countDocuments({ ...query, status: 'open' }),
        Task.countDocuments({ ...query, status: 'in_progress' }),
        Task.countDocuments({ ...query, status: 'pending_approval' }),
        Task.countDocuments({ ...query, status: 'completed' }),
        Task.countDocuments({ ...query, status: 'overdue' }),
        Task.countDocuments({ ...query, status: 'cancelled' }),
      ]);

    return {
      total,
      open,
      inProgress,
      pendingApproval,
      completed,
      overdue,
      cancelled,
    };
  }

  /**
   * 5. AUTOMATIC COMPLIANCE TASK GENERATION ENGINE
   *
   * Scans active compliance records and generates tasks for:
   * 1. Compliance approaching expiry (configurable milestones: 30d, 15d, 7d, 1d)
   * 2. Compliance expired
   * 3. Pending review/approval
   * 4. Missing mandatory documents
   * 5. Overdue compliance
   *
   * PREVENTS DUPLICATES:
   * Uses autoGenKey sparse unique indexing and checks for active tasks before creation.
   */
  public static async generateComplianceTasks(): Promise<{
    scannedRecordsCount: number;
    createdTasksCount: number;
    notificationsCount: number;
    details: Array<{ type: string; recordNumber: string; taskTitle: string }>;
  }> {
    // 1. Fetch Admin Settings for reminder intervals
    const settings = await Settings.findOne({ entity: null });
    const reminderDays: number[] = settings?.notifications?.defaultReminderDays?.length
      ? settings.notifications.defaultReminderDays
      : [30, 15, 7, 1];

    // Find default fallback admin
    const fallbackAdmin = await User.findOne({
      role: {
        $in: await User.find({ status: 'active' }).distinct('role'),
      },
    }).select('_id');

    const adminAssigneeId = fallbackAdmin?._id || new Types.ObjectId();

    // 2. Fetch compliance records
    const records = await ComplianceRecord.find({
      status: { $ne: 'not_applicable' },
    })
      .populate('entity', 'name entityCode owner')
      .populate('location', 'name locationCode manager')
      .populate('rule', 'name code category requiredDocuments renewalCycle')
      .populate('assignedUser', 'firstName lastName email fullName');

    const now = new Date();
    now.setHours(0, 0, 0, 0);

    let createdTasksCount = 0;
    let notificationsCount = 0;
    const details: Array<{ type: string; recordNumber: string; taskTitle: string }> = [];

    for (const record of records) {
      const rule = record.rule as any;
      const entity = record.entity as any;
      const location = record.location as any;

      const entityId = entity?._id || (record.populated?.('entity') ? null : record.entity);
      if (!entityId) {
        continue;
      }
      const locationId = location?._id || (record.populated?.('location') ? null : record.location);

      const ruleName = rule?.name || 'Statutory Compliance';
      const recordNumber = record.recordNumber;

      // Determine default responsible user
      const targetAssigneeId =
        (record.assignedUser as any)?._id ||
        location?.manager ||
        entity?.owner ||
        adminAssigneeId;

      // ── TRIGGER 1: Compliance Approaching Expiry ─────────────────────────────
      if (record.expiryDate && record.status !== 'expired') {
        const expiry = new Date(record.expiryDate);
        expiry.setHours(0, 0, 0, 0);
        const diffMs = expiry.getTime() - now.getTime();
        const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24));

        if (diffDays > 0) {
          // Check if diffDays matches any configured milestone (e.g. exactly <= milestone)
          const matchedMilestone = reminderDays.find(
            (m) => diffDays <= m && diffDays > (m === 1 ? 0 : m / 2)
          );

          if (matchedMilestone !== undefined) {
            const autoGenKey = `expiring_${record._id}_${matchedMilestone}d`;

            // Duplicate Prevention Check
            const existingTask = await Task.findOne({
              $or: [
                { autoGenKey },
                {
                  complianceRecord: record._id,
                  taskType: 'renewal',
                  status: { $in: ['open', 'in_progress', 'pending_approval'] },
                },
              ],
            });

            if (!existingTask) {
              const priority: TaskPriority =
                diffDays <= 7 ? 'critical' : diffDays <= 15 ? 'high' : 'medium';
              const title = `Compliance Expiring in ${diffDays}d: ${ruleName}`;
              const description = `Statutory compliance record ${recordNumber} for ${location?.name || 'Unit'} will expire on ${expiry.toLocaleDateString()}. Please prepare and file renewal documents.`;

              const newTask = await Task.create({
                title,
                description,
                entity: entityId,
                location: locationId,
                complianceRecord: record._id,
                assignedTo: targetAssigneeId,
                priority,
                dueDate: record.expiryDate,
                status: 'open',
                taskType: 'renewal',
                isAutoGenerated: true,
                autoGenSource: 'expiry_monitor',
                autoGenKey,
              });

              createdTasksCount++;
              details.push({ type: 'expiring_soon', recordNumber, taskTitle: title });

              // Dispatch Notification
              await NotificationService.dispatchNotification({
                recipientId: targetAssigneeId,
                type: 'compliance_expiring',
                title: `Compliance Expiring Soon (${diffDays} days)`,
                body: description,
                actionUrl: `/compliance/records/${record._id}`,
                relatedComplianceRecord: record._id,
                relatedTask: newTask._id,
                entity: entityId,
                emailData: {
                  ruleName,
                  recordNumber,
                  expiryDate: expiry.toLocaleDateString(),
                  daysLeft: diffDays,
                },
              });
              notificationsCount++;
            }
          }
        }
      }

      // ── TRIGGER 2: Compliance Expired ────────────────────────────────────────
      if (record.expiryDate) {
        const expiry = new Date(record.expiryDate);
        expiry.setHours(0, 0, 0, 0);

        if (expiry < now) {
          // Only a granted compliance can lapse. Records still moving through the
          // workflow keep their status so they can be submitted and reviewed.
          if (record.status === 'approved' || record.status === 'expiring_soon') {
            record.status = 'expired';
            await record.save();
          }

          const autoGenKey = `expired_${record._id}`;
          const existingExpiredTask = await Task.findOne({
            $or: [
              { autoGenKey },
              {
                complianceRecord: record._id,
                priority: 'critical',
                status: { $in: ['open', 'in_progress'] },
              },
            ],
          });

          if (!existingExpiredTask) {
            const title = `URGENT: Compliance Expired - ${ruleName}`;
            const description = `Statutory compliance obligation ${recordNumber} for ${location?.name || 'Unit'} expired on ${expiry.toLocaleDateString()}. Immediate renewal and statutory upload required.`;

            const newTask = await Task.create({
              title,
              description,
              entity: entityId,
              location: locationId,
              complianceRecord: record._id,
              assignedTo: targetAssigneeId,
              priority: 'critical',
              dueDate: new Date(),
              status: 'open',
              taskType: 'renewal',
              isAutoGenerated: true,
              autoGenSource: 'expired_checker',
              autoGenKey,
            });

            createdTasksCount++;
            details.push({ type: 'expired', recordNumber, taskTitle: title });

            // Notification
            await NotificationService.dispatchNotification({
              recipientId: targetAssigneeId,
              type: 'compliance_expired',
              title: `URGENT: Compliance Expired (${recordNumber})`,
              body: description,
              actionUrl: `/compliance/records/${record._id}`,
              relatedComplianceRecord: record._id,
              relatedTask: newTask._id,
              entity: entityId,
              emailData: {
                ruleName,
                recordNumber,
                expiryDate: expiry.toLocaleDateString(),
              },
            });
            notificationsCount++;
          }
        }
      }

      // ── TRIGGER 3: Pending Review / Approval ────────────────────────────────
      if (record.status === 'submitted' || record.status === 'under_review') {
        const autoGenKey = `pending_approval_${record._id}`;

        const existingApprovalTask = await Task.findOne({
          $or: [
            { autoGenKey },
            {
              complianceRecord: record._id,
              taskType: 'approval',
              status: { $in: ['open', 'in_progress', 'pending_approval'] },
            },
          ],
        });

        if (!existingApprovalTask) {
          const title = `Approval Required: ${ruleName} (${location?.name || 'Unit'})`;
          const description = `Statutory compliance documentation for record ${recordNumber} is awaiting official reviewer inspection and sign-off.`;

          const newTask = await Task.create({
            title,
            description,
            entity: entityId,
            location: locationId,
            complianceRecord: record._id,
            assignedTo: targetAssigneeId,
            priority: 'high',
            dueDate: record.dueDate || new Date(Date.now() + 7 * 86400000),
            status: 'pending_approval',
            taskType: 'approval',
            isAutoGenerated: true,
            autoGenSource: 'approval_monitor',
            autoGenKey,
          });

          createdTasksCount++;
          details.push({ type: 'pending_approval', recordNumber, taskTitle: title });

          await NotificationService.dispatchNotification({
            recipientId: targetAssigneeId,
            type: 'approval_required',
            title: `Statutory Review Required (${recordNumber})`,
            body: description,
            actionUrl: `/compliance/records/${record._id}`,
            relatedComplianceRecord: record._id,
            relatedTask: newTask._id,
            entity: entityId,
            emailData: {
              ruleName,
              recordNumber,
              locationName: location?.name || 'Assigned Unit',
            },
          });
          notificationsCount++;
        }
      }

      // ── TRIGGER 4: Missing Mandatory Documents ──────────────────────────────
      if (rule?.requiredDocuments && rule.requiredDocuments.length > 0) {
        const mandatoryDocTypes = rule.requiredDocuments.filter((d: any) => d.isMandatory);

        if (mandatoryDocTypes.length > 0) {
          const attachedCount = record.documents?.length || 0;

          if (attachedCount === 0 && (record.status === 'pending' || record.status === 'correction')) {
            const autoGenKey = `missing_docs_${record._id}`;

            const existingDocTask = await Task.findOne({
              $or: [
                { autoGenKey },
                {
                  complianceRecord: record._id,
                  taskType: 'document_upload',
                  status: { $in: ['open', 'in_progress'] },
                },
              ],
            });

            if (!existingDocTask) {
              const title = `Missing Evidence Upload: ${ruleName}`;
              const description = `Record ${recordNumber} requires mandatory statutory evidence documents before it can be submitted for review.`;

              const newTask = await Task.create({
                title,
                description,
                entity: entityId,
                location: locationId,
                complianceRecord: record._id,
                assignedTo: targetAssigneeId,
                priority: 'high',
                dueDate: record.dueDate || new Date(Date.now() + 5 * 86400000),
                status: 'open',
                taskType: 'document_upload',
                isAutoGenerated: true,
                autoGenSource: 'document_check',
                autoGenKey,
              });

              createdTasksCount++;
              details.push({ type: 'missing_documents', recordNumber, taskTitle: title });
            }
          }
        }
      }

      // ── TRIGGER 5: Overdue Compliance ───────────────────────────────────────
      if (record.dueDate && (record.status === 'pending' || record.status === 'correction')) {
        const dueDate = new Date(record.dueDate);
        dueDate.setHours(0, 0, 0, 0);

        if (dueDate < now) {
          const autoGenKey = `overdue_submission_${record._id}`;

          const existingOverdueTask = await Task.findOne({
            $or: [
              { autoGenKey },
              {
                complianceRecord: record._id,
                status: { $in: ['open', 'in_progress', 'overdue'] },
                dueDate: { $lt: now },
              },
            ],
          });

          if (!existingOverdueTask) {
            const title = `OVERDUE: Compliance Submission - ${ruleName}`;
            const description = `Statutory deadline (${dueDate.toLocaleDateString()}) for record ${recordNumber} has passed without submission. Immediate action required.`;

            const newTask = await Task.create({
              title,
              description,
              entity: entityId,
              location: locationId,
              complianceRecord: record._id,
              assignedTo: targetAssigneeId,
              priority: 'critical',
              dueDate: record.dueDate,
              status: 'overdue',
              taskType: 'manual',
              isAutoGenerated: true,
              autoGenSource: 'overdue_check',
              autoGenKey,
            });

            createdTasksCount++;
            details.push({ type: 'overdue_compliance', recordNumber, taskTitle: title });

            await NotificationService.dispatchNotification({
              recipientId: targetAssigneeId,
              type: 'task_overdue',
              title: `Statutory Submission Overdue: ${ruleName}`,
              body: description,
              actionUrl: `/compliance/records/${record._id}`,
              relatedComplianceRecord: record._id,
              relatedTask: newTask._id,
              entity: entityId,
              emailData: {
                taskTitle: title,
                dueDate: dueDate.toLocaleDateString(),
                priority: 'critical',
              },
            });
            notificationsCount++;
          }
        }
      }
    }

    return {
      scannedRecordsCount: records.length,
      createdTasksCount,
      notificationsCount,
      details,
    };
  }
}

export const taskAutomationService = TaskAutomationService;

