/**
 * Task Model
 *
 * Action items tied to compliance renewals, approvals, or manual assignments.
 * Maps to Phase 5: Tasks & Notifications → Work Management.
 *
 * Tasks are auto-generated by the renewal engine OR manually created.
 * References: User (assignee), Entity, Location, ComplianceRecord (optional).
 */

import mongoose, { Schema, Document, Model, Types } from 'mongoose';
import type { TaskStatus, TaskPriority, Ref } from '../types/models.js';

// ── Comment (embedded) ────────────────────────────────────────────────────────

export interface ITaskComment {
  _id: Types.ObjectId;
  author: Ref<unknown>;    // → User
  text: string;
  createdAt: Date;
}

const taskCommentSchema = new Schema<ITaskComment>(
  {
    author:    { type: Schema.Types.ObjectId, ref: 'User', required: true },
    text:      { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
  },
  { _id: true }
);

// ── Task document ──────────────────────────────────────────────────────────────

export interface ITask extends Document {
  _id: Types.ObjectId;
  title: string;
  description?: string;

  // Classification
  taskType: 'renewal' | 'approval' | 'document_upload' | 'inspection' | 'manual';
  category?: Ref<unknown>;    // → MasterData (task_category)

  // Scoping
  entity: Ref<unknown>;       // → Entity
  location?: Ref<unknown>;    // → Location
  complianceRecord?: Ref<unknown>; // → ComplianceRecord (if task is compliance-driven)
  licence?: Ref<unknown>;     // → Licence (if task is licence-driven)

  // Assignment
  assignedTo: Ref<unknown>;   // → User
  assignedBy?: Ref<unknown>;  // → User
  assignedAt?: Date;

  // Dates
  dueDate: Date;
  completedAt?: Date;
  completedBy?: Ref<unknown>; // → User
  startedAt?: Date;

  // Priority & status
  priority: TaskPriority;
  status: TaskStatus;

  // Escalation
  isEscalated: boolean;
  escalatedTo?: Ref<unknown>; // → User
  escalatedAt?: Date;
  escalationReason?: string;

  // Auto-gen metadata
  isAutoGenerated: boolean;
  autoGenSource?: string;     // e.g. "renewal_job", "expiry_check"
  autoGenKey?: string;        // Deduplication key e.g. `${complianceRecordId}_${reason}`

  comments: ITaskComment[];
  tags?: string[];

  createdBy?: Ref<unknown>;
  updatedBy?: Ref<unknown>;
  createdAt: Date;
  updatedAt: Date;
}

const taskSchema = new Schema<ITask>(
  {
    title:       { type: String, required: true, trim: true },
    description: { type: String },

    taskType: {
      type: String,
      required: true,
      enum: ['renewal', 'approval', 'document_upload', 'inspection', 'manual'],
      default: 'manual',
    },
    category: { type: Schema.Types.ObjectId, ref: 'MasterData' },

    entity:           { type: Schema.Types.ObjectId, ref: 'Entity', required: true },
    location:         { type: Schema.Types.ObjectId, ref: 'Location' },
    complianceRecord: { type: Schema.Types.ObjectId, ref: 'ComplianceRecord' },
    licence:          { type: Schema.Types.ObjectId, ref: 'Licence' },

    assignedTo: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    assignedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    assignedAt: { type: Date, default: Date.now },

    dueDate:     { type: Date, required: true },
    completedAt: { type: Date },
    completedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    startedAt:   { type: Date },

    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'critical'],
      default: 'medium',
    },
    status: {
      type: String,
      enum: ['open', 'in_progress', 'pending_approval', 'completed', 'overdue', 'cancelled'],
      default: 'open',
    },

    isEscalated:      { type: Boolean, default: false },
    escalatedTo:      { type: Schema.Types.ObjectId, ref: 'User' },
    escalatedAt:      { type: Date },
    escalationReason: { type: String },

    isAutoGenerated: { type: Boolean, default: false },
    autoGenSource:   { type: String },
    autoGenKey:      { type: String, trim: true },

    comments: { type: [taskCommentSchema], default: [] },
    tags:     { type: [String], default: [] },

    createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

// ── Indexes ────────────────────────────────────────────────────────────────────
taskSchema.index({ assignedTo: 1, status: 1 });
taskSchema.index({ entity: 1, status: 1 });
taskSchema.index({ location: 1, status: 1 });
taskSchema.index({ dueDate: 1, status: 1 });       // Overdue job
taskSchema.index({ complianceRecord: 1, status: 1 });
taskSchema.index({ autoGenKey: 1 }, { unique: true, sparse: true }); // Prevent duplicate tasks
taskSchema.index({ isEscalated: 1 });

const Task: Model<ITask> = mongoose.model<ITask>('Task', taskSchema);
export default Task;
